<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 11px; color: #17202a; }
        h1 { font-size: 18px; color: #055236; margin-bottom: 4px; }
        .meta { color: #6c757d; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #dee2e6; padding: 6px 8px; text-align: left; }
        th { background: #055236; color: #fff; }
        tr:nth-child(even) { background: #f8f9fa; }
        .priority-emergency { color: #dc3545; font-weight: bold; }
        .priority-high { color: #b8860b; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Maintenance Requests Report</h1>
    <div class="meta">Generated by {{ $generatedBy }} on {{ $generatedAt->format('M j, Y H:i') }}</div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Tenant</th>
                <th>Property</th>
                <th>Unit</th>
                <th>Category</th>
                <th>Subject</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Submitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($requests as $r)
                <tr>
                    <td>{{ $r->id }}</td>
                    <td>{{ $r->tenant && $r->tenant->user ? $r->tenant->user->full_name : '-' }}</td>
                    <td>{{ $r->property ? $r->property->name : '-' }}</td>
                    <td>{{ $r->unit ? $r->unit->unit_number : '-' }}</td>
                    <td>{{ ucfirst($r->category) }}</td>
                    <td>{{ $r->subject ?? '-' }}</td>
                    <td class="priority-{{ $r->priority }}">{{ ucfirst($r->priority) }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $r->status)) }}</td>
                    <td>{{ optional($r->submitted_at)->format('M j, Y') }}</td>
                </tr>
            @empty
                <tr><td colspan="9">No maintenance requests found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>