<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Maintenance Requests Report</title>
    @include('exports._pdf_styles')
</head>

<body>

    {{-- ===== Header ===== --}}
    <div class="pdf-header">
        <table>
            <tr>
                <td class="logo-cell">
                    <div class="logo-circle">
                        <img src="{{ public_path('images/logo.jpg') }}" alt="Logo">
                    </div>
                </td>
                <td class="brand-cell">
                    <div class="brand-name">Rental System</div>
                    <div class="report-title">Maintenance Requests Report</div>
                </td>
                <td class="meta-cell">
                    Generated by {{ $generatedBy }}<br>
                    {{ $generatedAt->format('d M Y, H:i') }}<br>
                    Total records: {{ $requests->count() }}
                </td>
            </tr>
        </table>
    </div>

    {{-- ===== Filters ===== --}}
    @if (!empty($filters))
        <div class="filters-bar">
            <strong>Filters applied:</strong>
            @foreach ($filters as $label => $value)
                {{ $label }}: {{ $value }}@if (!$loop->last)
                    &nbsp;|&nbsp;
                @endif
            @endforeach
        </div>
    @endif

    {{-- ===== Table ===== --}}
    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tenant</th>
                <th>Property</th>
                <th>Unit</th>
                <th>Category</th>
                <th>Subject</th>
                <th>Priority</th>
                <th>Status</th>
                <th>Submitted</th>
            </tr>
        </thead>
        <tbody>
            @forelse($requests as $r)
                <tr>
                    <td>{{ $r->id }}</td>
                    <td>{{ $r->tenant && $r->tenant->user ? $r->tenant->user->full_name : '-' }}</td>
                    <td>{{ $r->property ? $r->property->name : '-' }}</td>
                    <td>{{ $r->unit ? $r->unit->unit_number : '-' }}</td>
                    <td>{{ ucfirst($r->category) }}</td>
                    <td>{{ $r->subject ?? '-' }}</td>
                    <td class="priority-{{ $r->priority }}">{{ ucfirst($r->priority) }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $r->status)) }}</td>
                    <td>{{ optional($r->submitted_at)->format('d M Y') ?? '-' }}</td>
                </tr>
            @empty
                <tr class="empty-row">
                    <td colspan="9">No maintenance requests found matching the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- ===== Totals ===== --}}
    @if ($requests->count() > 0)
        @php
            $pending = $requests->whereIn('status', ['submitted', 'assigned', 'in_progress'])->count();
            $resolved = $requests->whereIn('status', ['resolved', 'confirmed'])->count();
            $rejected = $requests->where('status', 'rejected')->count();
            $emergency = $requests->where('priority', 'emergency')->count();
        @endphp
        <div class="totals-bar">
            Open: {{ $pending }}
            &nbsp;|&nbsp;
            Resolved: {{ $resolved }}
            &nbsp;|&nbsp;
            Rejected: {{ $rejected }}
            @if ($emergency > 0)
                &nbsp;|&nbsp; <span style="color:#dc2626;">Emergency priority: {{ $emergency }}</span>
            @endif
        </div>
    @endif

    {{-- ===== Footer ===== --}}
    <div class="pdf-footer">
        Rental System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; Generated {{ $generatedAt->format('d M Y, H:i') }}
    </div>

</body>

</html>
