<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: sans-serif; font-size: 11px; color: #17202a; }
        h1 { font-size: 18px; color: #055236; margin-bottom: 4px; }
        .meta { color: #6c757d; font-size: 10px; margin-bottom: 16px; }
        table { width: 100%; border-collapse: collapse; }
        th, td { border: 1px solid #dee2e6; padding: 6px 8px; text-align: left; }
        th { background: #055236; color: #fff; }
        tr:nth-child(even) { background: #f8f9fa; }
        .status-completed { color: #198754; font-weight: bold; }
        .status-pending { color: #b8860b; font-weight: bold; }
        .status-failed { color: #dc3545; font-weight: bold; }
    </style>
</head>
<body>
    <h1>Payments Report</h1>
    <div class="meta">Generated by {{ $generatedBy }} on {{ $generatedAt->format('M j, Y H:i') }}</div>

    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Tenant</th>
                <th>Unit</th>
                <th>Amount</th>
                <th>Due Date</th>
                <th>Status</th>
                <th>Receipt</th>
            </tr>
        </thead>
        <tbody>
            @forelse ($payments as $p)
                <tr>
                    <td>{{ $p->id }}</td>
                    <td>{{ $p->tenant && $p->tenant->user ? $p->tenant->user->full_name : '-' }}</td>
                    <td>{{ $p->unit ? $p->unit->unit_number : '-' }}</td>
                    <td>{{ number_format((float) $p->amount, 2) }}</td>
                    <td>{{ optional($p->due_date)->format('M j, Y') }}</td>
                    <td class="status-{{ $p->status }}">{{ ucfirst($p->status) }}</td>
                    <td>{{ $p->receipt_url ?? '-' }}</td>
                </tr>
            @empty
                <tr><td colspan="7">No payments found.</td></tr>
            @endforelse
        </tbody>
    </table>
</body>
</html>