<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Payments Report</title>
    @include('exports._pdf_styles')
</head>

<body>

    {{-- ===== Header ===== --}}
    <div class="pdf-header">
        <table>
            <tr>
                <td class="logo-cell">
                    <div class="logo-circle">
                        <img src="{{ public_path('images/logo.jpg') }}" alt="Logo">
                    </div>
                </td>
                <td class="brand-cell">
                    <div class="brand-name">Rental System</div>
                    <div class="report-title">Payments Report</div>
                </td>
                <td class="meta-cell">
                    Generated by {{ $generatedBy }}<br>
                    {{ $generatedAt->format('d M Y, H:i') }}<br>
                    Total records: {{ $payments->count() }}
                </td>
            </tr>
        </table>
    </div>

    {{-- ===== Filters ===== --}}
    @if (!empty($filters))
        <div class="filters-bar">
            <strong>Filters applied:</strong>
            @foreach ($filters as $label => $value)
                {{ $label }}: {{ $value }}@if (!$loop->last)
                    &nbsp;|&nbsp;
                @endif
            @endforeach
        </div>
    @endif

    {{-- ===== Table ===== --}}
    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Tenant</th>
                <th>Unit</th>
                <th>Amount (KES)</th>
                <th>Due Date</th>
                <th>Payment Date</th>
                <th>Status</th>
                <th>Transaction ID</th>
                <th>Receipt</th>
            </tr>
        </thead>
        <tbody>
            @forelse($payments as $p)
                <tr>
                    <td>{{ $p->id }}</td>
                    <td>{{ $p->tenant && $p->tenant->user ? $p->tenant->user->full_name : '-' }}</td>
                    <td>{{ $p->unit ? $p->unit->unit_number : '-' }}</td>
                    <td>{{ number_format((float) $p->amount, 2) }}</td>
                    <td>{{ optional($p->due_date)->format('d M Y') ?? '-' }}</td>
                    <td>{{ optional($p->payment_date)->format('d M Y') ?? '-' }}</td>
                    <td class="status-{{ $p->status }}">{{ ucfirst(str_replace('_', ' ', $p->status)) }}</td>
                    <td>{{ $p->transaction_id ?? '-' }}</td>
                    <td>{{ $p->receipt_url ?? '-' }}</td>
                </tr>
            @empty
                <tr class="empty-row">
                    <td colspan="9">No payments found matching the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    {{-- ===== Totals ===== --}}
    @if ($payments->count() > 0)
        @php
            $total = $payments->sum('amount');
            $completed = $payments->where('status', 'completed')->sum('amount');
            $pending = $payments->whereIn('status', ['pending', 'awaiting_verification'])->count();
        @endphp
        <div class="totals-bar">
            Total amount: KES {{ number_format((float) $total, 2) }}
            &nbsp;|&nbsp;
            Completed: KES {{ number_format((float) $completed, 2) }}
            &nbsp;|&nbsp;
            Pending / awaiting verification: {{ $pending }}
        </div>
    @endif

    {{-- ===== Footer ===== --}}
    <div class="pdf-footer">
        Rental System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; Generated {{ $generatedAt->format('d M Y, H:i') }}
    </div>

</body>

</html>
