<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Properties Report</title>
    @include('exports._pdf_styles')
</head>

<body>

    <div class="pdf-header">
        <table>
            <tr>
                <td class="logo-cell">
                    <div class="logo-circle">
                        <img src="{{ public_path('images/logo.jpg') }}" alt="Logo">
                    </div>
                </td>
                <td class="brand-cell">
                    <div class="brand-name">Rental System</div>
                    <div class="report-title">Properties Report</div>
                </td>
                <td class="meta-cell">
                    Generated by {{ $generatedBy }}<br>
                    {{ $generatedAt->format('d M Y, H:i') }}<br>
                    Total records: {{ $properties->count() }}
                </td>
            </tr>
        </table>
    </div>

    @if (!empty($filters))
        <div class="filters-bar">
            <strong>Filters applied:</strong>
            @foreach ($filters as $label => $value)
                {{ $label }}: {{ $value }}@if (!$loop->last)
                    &nbsp;|&nbsp;
                @endif
            @endforeach
        </div>
    @endif

    @php
        $totalUnits = 0;
        $totalOccupied = 0;
    @endphp

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Property Name</th>
                <th>Landlord</th>
                <th>Address</th>
                <th>Type</th>
                <th>Units</th>
                <th>Occupied</th>
                <th>Available</th>
                <th>Caretaker</th>
            </tr>
        </thead>
        <tbody>
            @forelse($properties as $p)
                @php
                    $units = $p->units ?? collect();
                    $occupied = $units->where('status', 'occupied')->count();
                    $available = $units->where('status', 'available')->count();
                    $totalUnits += $units->count();
                    $totalOccupied += $occupied;
                @endphp
                <tr>
                    <td>{{ $p->id }}</td>
                    <td>{{ $p->name }}</td>
                    <td>{{ $p->landlord && $p->landlord->user ? $p->landlord->user->full_name : '-' }}</td>
                    <td>{{ $p->address ?? '-' }}</td>
                    <td>{{ $p->type ?? '-' }}</td>
                    <td>{{ $units->count() }}</td>
                    <td>{{ $occupied }}</td>
                    <td>{{ $available }}</td>
                    <td>{{ $p->caretaker && $p->caretaker->user ? $p->caretaker->user->full_name : 'Unassigned' }}</td>
                </tr>
            @empty
                <tr class="empty-row">
                    <td colspan="9">No properties found matching the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if ($properties->count() > 0)
        <div class="totals-bar">
            Total units: {{ $totalUnits }}
            &nbsp;|&nbsp;
            Occupied: {{ $totalOccupied }}
            &nbsp;|&nbsp;
            Available: {{ $totalUnits - $totalOccupied }}
            &nbsp;|&nbsp;
            Occupancy rate: {{ $totalUnits > 0 ? number_format(($totalOccupied / $totalUnits) * 100, 1) : '0.0' }}%
        </div>
    @endif

    <div class="pdf-footer">
        Rental System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; Generated {{ $generatedAt->format('d M Y, H:i') }}
    </div>

</body>

</html>
