<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Users Report</title>
    @include('exports._pdf_styles')
</head>

<body>

    <div class="pdf-header">
        <table>
            <tr>
                <td class="logo-cell">
                    <div class="logo-circle">
                        <img src="{{ public_path('images/logo.jpg') }}" alt="Logo">
                    </div>
                </td>
                <td class="brand-cell">
                    <div class="brand-name">Rental System</div>
                    <div class="report-title">System Users Report</div>
                </td>
                <td class="meta-cell">
                    Generated by {{ $generatedBy }}<br>
                    {{ $generatedAt->format('d M Y, H:i') }}<br>
                    Total records: {{ $users->count() }}
                </td>
            </tr>
        </table>
    </div>

    @if (!empty($filters))
        <div class="filters-bar">
            <strong>Filters applied:</strong>
            @foreach ($filters as $label => $value)
                {{ $label }}: {{ $value }}@if (!$loop->last)
                    &nbsp;|&nbsp;
                @endif
            @endforeach
        </div>
    @endif

    <table class="data-table">
        <thead>
            <tr>
                <th>ID</th>
                <th>Full Name</th>
                <th>Username</th>
                <th>Email</th>
                <th>Phone</th>
                <th>Role</th>
                <th>Status</th>
                <th>Last Login</th>
                <th>Registered</th>
            </tr>
        </thead>
        <tbody>
            @forelse($users as $u)
                <tr>
                    <td>{{ $u->id }}</td>
                    <td>{{ $u->full_name }}</td>
                    <td>{{ $u->username ?? '-' }}</td>
                    <td>{{ $u->email }}</td>
                    <td>{{ $u->phone ?? '-' }}</td>
                    <td>{{ ucfirst($u->role) }}</td>
                    <td class="{{ $u->is_active ? 'status-completed' : 'status-failed' }}">
                        {{ $u->is_active ? 'Active' : 'Inactive' }}
                    </td>
                    <td>{{ optional($u->last_login)->format('d M Y') ?? 'Never' }}</td>
                    <td>{{ optional($u->created_at)->format('d M Y') ?? '-' }}</td>
                </tr>
            @empty
                <tr class="empty-row">
                    <td colspan="9">No users found matching the selected filters.</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    @if ($users->count() > 0)
        @php
            $active = $users->where('is_active', true)->count();
        @endphp
        <div class="totals-bar">
            Active: {{ $active }}
            &nbsp;|&nbsp;
            Inactive: {{ $users->count() - $active }}
            &nbsp;|&nbsp;
            Landlords: {{ $users->where('role', 'landlord')->count() }}
            &nbsp;|&nbsp;
            Tenants: {{ $users->where('role', 'tenant')->count() }}
            &nbsp;|&nbsp;
            Caretakers: {{ $users->where('role', 'caretaker')->count() }}
        </div>
    @endif

    <div class="pdf-footer">
        Rental System &nbsp;|&nbsp; Confidential &nbsp;|&nbsp; Generated {{ $generatedAt->format('d M Y, H:i') }}
    </div>

</body>

</html>
